"""Load search-based IGDB candidates for the current RAWG corpus."""

from __future__ import annotations

import json
import os
from pathlib import Path

from src.ingestion.cli import build_common_parser
from src.ingestion.igdb_auth import load_igdb_settings
from src.ingestion.igdb_client import IGDBClient
from src.ingestion.jobs.select_igdb_search_seeds import select_igdb_search_seeds_from_rows
from src.ingestion.pipeline_log import PipelineRunLogger


def default_seed_limit() -> int:
    settings = load_igdb_settings()
    return int(os.getenv("IGDB_SEARCH_LIMIT", settings.get("demo_limit", 50)))


def default_result_limit() -> int:
    return int(os.getenv("IGDB_SEARCH_RESULT_LIMIT", "5"))


def build_source_record_id(
    seed: dict[str, object],
    query: dict[str, str],
    candidate_id: str,
) -> str:
    return f'{seed["source"]}:{seed["source_game_id"]}:{query["query_strategy"]}:{candidate_id}'


def build_empty_result_record_id(seed: dict[str, object], query: dict[str, str]) -> str:
    return f'{seed["source"]}:{seed["source_game_id"]}:{query["query_strategy"]}:__empty__'


def load_seeds(client: IGDBClient, args) -> list[dict[str, object]]:  # type: ignore[no-untyped-def]
    if getattr(args, "input_file", None):
        return json.loads(Path(args.input_file).read_text(encoding="utf-8"))
    if client.repository is None:
        return []
    rawg_rows = client.repository.fetch_staging_rows("stg.source_games", source="rawg")
    external_rows = client.repository.fetch_staging_rows(
        "stg.source_game_external_ids", source="wikidata"
    )
    alias_rows = client.repository.fetch_staging_rows("stg.source_game_aliases", source="wikidata")
    existing_rows = (
        client.repository.fetch_igdb_search_candidates(source_name="rawg")
        if args.missing_only
        else []
    )
    return select_igdb_search_seeds_from_rows(
        rawg_rows=rawg_rows,
        external_rows=external_rows,
        alias_rows=alias_rows,
        existing_candidate_rows=existing_rows,
        limit=args.limit,
        alias_limit=args.alias_limit,
        unmatched_only=args.unmatched_only,
        missing_only=args.missing_only,
    )


def main(argv: list[str] | None = None) -> int:
    parser = build_common_parser("Load search-based IGDB candidate rows.")
    parser.add_argument(
        "--input-file",
        help="Optional JSON file generated by select_igdb_search_seeds.",
    )
    parser.add_argument("--alias-limit", type=int, default=2)
    parser.add_argument("--result-limit", type=int, default=default_result_limit())
    parser.add_argument("--year-window", type=int, default=1)
    parser.add_argument("--unmatched-only", action="store_true")
    parser.add_argument("--missing-only", action="store_true")
    parser.set_defaults(limit=default_seed_limit())
    args = parser.parse_args(argv)

    client = IGDBClient()
    logger = PipelineRunLogger(
        pipeline_name="igdb_search",
        stage_name="raw",
        repository=None if args.dry_run else client.repository,
    )
    logger.mark_started(
        parameters={
            "dry_run": args.dry_run,
            "seed_limit": args.limit,
            "result_limit": args.result_limit,
            "unmatched_only": args.unmatched_only,
            "missing_only": args.missing_only,
        }
    )

    seeds = load_seeds(client, args)
    if args.dry_run:
        print(
            {
                "seed_count": len(seeds),
                "result_limit": args.result_limit,
                "year_window": args.year_window,
                "sample": seeds[:2],
            }
        )
        logger.mark_finished(status="completed", metrics={"planned_seed_count": len(seeds)})
        return 0

    if not seeds:
        raise RuntimeError(
            "No IGDB search seeds available. "
            "Run `make rawg-staging` and `make wikidata-staging` first."
        )
    if client.repository is None:
        raise RuntimeError("Database repository is unavailable for IGDB search load.")

    client.repository.ensure_igdb_search_results_table()
    inserted_search_rows = 0
    cached_game_rows = 0
    searched_records = 0
    for seed in seeds:
        release_year = int(seed["release_year"]) if seed.get("release_year") is not None else None
        for query in seed.get("queries", []):
            if not isinstance(query, dict):
                continue
            query_text = str(query.get("query_text") or "").strip()
            query_strategy = str(query.get("query_strategy") or "").strip()
            if not query_text or not query_strategy:
                continue
            response = client.search_games(
                query_text,
                limit=args.result_limit,
                release_year=release_year,
                year_window=max(0, args.year_window),
                dry_run=False,
                force_refresh=args.force_refresh,
                from_cache_only=args.from_cache_only,
            )
            payload = response.payload if isinstance(response.payload, list) else []
            if not payload:
                wrapped_payload = {
                    "anchor": {
                        "source": seed.get("source"),
                        "source_game_id": seed.get("source_game_id"),
                        "name": seed.get("name"),
                        "slug": seed.get("slug"),
                        "release_year": seed.get("release_year"),
                        "matched_to_wikidata": seed.get("matched_to_wikidata"),
                    },
                    "query": {
                        "text": query_text,
                        "strategy": query_strategy,
                        "rank": None,
                    },
                    "candidate": None,
                }
                client.repository.insert_raw_record(
                    table_name="raw.igdb_search_results",
                    endpoint=response.endpoint,
                    request_hash=response.request_hash,
                    source_record_id=build_empty_result_record_id(seed, query),
                    response_json=wrapped_payload,
                    response_hash=response.response_hash,
                    response_storage_path=response.cache_path,
                    from_cache=response.from_cache,
                    http_status=response.http_status,
                    error_message=response.error_message,
                )
                searched_records += 1
                continue
            for rank, item in enumerate(payload, start=1):
                if not isinstance(item, dict):
                    continue
                candidate_id = str(item.get("id") or "").strip()
                if not candidate_id:
                    continue
                wrapped_payload = {
                    "anchor": {
                        "source": seed.get("source"),
                        "source_game_id": seed.get("source_game_id"),
                        "name": seed.get("name"),
                        "slug": seed.get("slug"),
                        "release_year": seed.get("release_year"),
                        "matched_to_wikidata": seed.get("matched_to_wikidata"),
                    },
                    "query": {
                        "text": query_text,
                        "strategy": query_strategy,
                        "rank": rank,
                    },
                    "candidate": item,
                }
                client.repository.insert_raw_record(
                    table_name="raw.igdb_search_results",
                    endpoint=response.endpoint,
                    request_hash=response.request_hash,
                    source_record_id=build_source_record_id(seed, query, candidate_id),
                    response_json=wrapped_payload,
                    response_hash=response.response_hash,
                    response_storage_path=response.cache_path,
                    from_cache=response.from_cache,
                    http_status=response.http_status,
                    error_message=response.error_message,
                )
                client.repository.insert_raw_record(
                    table_name="raw.igdb_games",
                    endpoint=response.endpoint,
                    request_hash=response.request_hash,
                    source_record_id=candidate_id,
                    response_json=item,
                    response_hash=response.response_hash,
                    response_storage_path=response.cache_path,
                    from_cache=response.from_cache,
                    http_status=response.http_status,
                    error_message=response.error_message,
                )
                inserted_search_rows += 1
                cached_game_rows += 1
            searched_records += 1
    logger.mark_finished(
        status="completed",
        metrics={
            "seed_count": len(seeds),
            "searched_records": searched_records,
            "search_rows": inserted_search_rows,
            "igdb_game_rows": cached_game_rows,
        },
    )
    print(
        {
            "seed_count": len(seeds),
            "searched_records": searched_records,
            "search_rows": inserted_search_rows,
            "igdb_game_rows": cached_game_rows,
        }
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
